## Numpy Learning Notebook
created by Minhyeok Park <pmh_only@pmh.codes>

In [2]:
# install requirements
%pip install -r ./requirements.txt

import numpy as np


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
# create new numpy array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [4]:
# retrieve element
arr = np.array([1, 2, 3, 4])
arr[0]

np.int64(1)

In [5]:
# array slicing
arr = np.array([1, 2, 3, 4])

print(arr[1:])
print(arr[:3])
print(arr[1:3])
print(arr[1:-1])

[2 3 4]
[1 2 3]
[2 3]
[2 3]


In [6]:
# array datatypes
arr = np.array([1, 2, 3, 4])
arr2 = np.array(['a', 'b', 'c', 'd'])
arr3 = np.array([False, True, False, True])
arr4 = np.array([1.2, 2.4, 3.6, 4.3])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

int64
<U1
bool
float64


In [7]:
# array copy
arr = np.array([1, 2, 3, 4])
arr2 = arr.copy()

arr2[3] = 5

print(arr, arr2)

[1 2 3 4] [1 2 3 5]


In [8]:
# array view
arr = np.array([1, 2, 3, 4])
arr2 = arr.view()

arr2[3] = 5

print(arr, arr2)

[1 2 3 5] [1 2 3 5]


In [9]:
# 2d array
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# array shape
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr.shape

(3, 4)

In [11]:
# fixed array shape
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
], ndmin=5)

arr.shape

(1, 1, 1, 3, 4)

In [12]:
# reshape array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(3, 4)

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# iterate array
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [14]:
# concat array
arr = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

arr3 = np.concat((arr, arr2))
arr3

array([1, 2, 3, 1, 2, 3])

In [15]:
# concat array (2d)
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr2 = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

print(np.concat((arr, arr2), axis=0), end="\n\n")
print(np.concat((arr, arr2), axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


In [16]:
# stack array (2d)
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr2 = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

print(np.stack((arr, arr2), axis=0), end="\n\n")
print(np.stack((arr, arr2), axis=1))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

[[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 9 10 11 12]]]


In [17]:
# hstack array (2d)
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr2 = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

np.hstack((arr, arr2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [18]:
# vstack array (2d)
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr2 = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

np.vstack((arr, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# dstack array (2d)
arr = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

arr2 = np.array([
  [ 1,  2,  3,  4 ],
  [ 5,  6,  7,  8 ],
  [ 9, 10, 11, 12 ]
])

np.dstack((arr, arr2))

array([[[ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4]],

       [[ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8]],

       [[ 9,  9],
        [10, 10],
        [11, 11],
        [12, 12]]])

In [20]:
# split array (2d)
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print(np.array_split(arr, 3, axis=0))
print(np.array_split(arr, 3, axis=1))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


In [23]:
# search array : return index of evens
arr = np.arange(1, 10)
arr2 = np.where(arr % 2 == 0)

arr2

(array([1, 3, 5, 7]),)

In [61]:
# filter array : return value of evens
arr = np.arange(1, 10)
arr2 = []

for x in arr:
  arr2.append(x % 2 == 0)

arr[arr2]

array([2, 4, 6, 8])

In [25]:
# sort array
arr = np.array([6, 3, 1, 6, 3, 2, 4])
arr2 = np.sort(arr)

arr2

array([1, 2, 3, 3, 4, 6, 6])

In [30]:
# sort array (2d)
arr = np.array([
  [1, 6, 7, 4],
  [6, 3, 2, 4]
])
arr2 = np.sort(arr)

arr2

array([[1, 4, 6, 7],
       [2, 3, 4, 6]])